### PR TITLE
Add ArrayPrimitiveTypeExpressionFactory

### PR DESCRIPTION
**Pull request by deipax**
When cloning Primitives all that needs to be done is copy the source
array to the target array.  Instead of calling the
PrimitiveTypeExpressionFactory call for every element you can use the
static Array.Copy method to assist.

Depending upon the primitive type, the performance gain is different.
In the tests I have, which are coded against 4.6.1, will have a
performance gain of any where from about 98% to almost 225%.  Byte
Array, for whatever reason, has a performance gain of about 6800% ... I
have no idea why byte arrays are so much different.

Int Arrays go from about 2,386,634 ops per sec to 4,727,659 (98% increase)
String arrays go from about 1,926,782 ops per sec to 5,730,086 (197% increase)
TimeSpan arrays go from about 1,988,071 ops per sec to 4,650,697 (133% increase)
DateTime arrays go from about 1,930,501 ops per sec to 4,210,105 (118% increase)
Delegate arrays go from about 1,659,751 ops per sec to 5,404,864 (225% increase)
Byte arrays go from about 58,083 ops per sec to 4,053,648 (6879% increase)

I would like supply a unit test to easily display the difference in
performance in the master project, but given the interface, it is not
exactly straight forward.  I generated the numbers above from running
the changes suggested from a local release build in my current test
setup.

### CODE REVIEW

**Comment by deipax** [comment]
For the polymorphism support, I should have likely created a new fork and made my changes there.  My apologies, I am fairly new to github and am still learning its nuances.

**Comment by MarcinJuraszek** [comment]
I'm happy to merge the perf improvements for arrays of primitive types, but for the other change related to polymorphism I would need more time to look into more closely because it has much greater implications on the library.

Would you mind reverting your last commit so I can accept this PR sending another one for the rest of the changes?

**Comment by deipax** [comment]
Done.  There is a similar performance increase for supplying an ExpressionFactory for a List<> of primitives (actually, the difference is more pronounced).  I will add that soon.  For the polymorphism support, I will for a new branch and put my work there soon.

Have you considered a mechanism that would allow users to specify their own expression factories so they may override default behavior by supplying their own implementations?

**Comment by deipax** [comment]
Hmm ... apparently I can have only one fork of the branch at a time.  Which pretty prevents parallel development since a pull request grab all difference from the base branch at a time (no way to isolate a change set like there is in TFS).

**Comment by MarcinJuraszek** [comment]
You should not be developing in your master branch, but instead create separate branches for each of the features/changes you're working on. Once they are ready you can request a Pull Request from a non-master branch of yours.

**Pull request merged**
